name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[s3]
    - name: Download dataset directly
      run: |
        mkdir -p data
        wget https://raw.githubusercontent.com/selva86/datasets/master/winequality-red.csv -O data/winequality-red.csv

    - name: Run training
      run: |
        python src/train.py
